import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BOARD)
GPIO.setup(37,GPIO.OUT)
GPIO.output(37,True)
GPIO.output(37,False)
GPIO.output(37,True)
GPIO.output(37,False)
print("This is 2 time on and off")
myPWM = GPIO.PWM(37,100)
#myPWM.start(50)
#myPWM.stop(50)
#myPWM.stop(10)
#myPWM.start(10)
#myPWM.ChangeDutyCycle(75)
myPWM.stop()
GPIO.cleanup()